name: donut
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - pip:
    - donut-python==1.0.9
    - transformers == 4.11.3
    - pytorch-lightning == 1.6.4
    - torch == 1.11.0
    - torchvision == 0.12.0
    - timm == 0.5.4
    - azureml-mlflow
    - mlflow
    - protobuf==3.20.0
    - numpy
    